idle_bg = "#363636"
idle_fg = "#ffffff"
info_bg = "#fdf8d8"
info_fg = "#000000"
good_bg = "#fdf8d8"
good_fg = "#000000"
warning_bg = "#fdd276"
warning_fg = "#000000"
critical_bg = "#e45148"
critical_fg = "#ffffff"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
